theme: jekyll-theme-minimal
title: D13 Design LLC - web application design and development for the creative business
description: D13 design is a small design and development team with a passion for creating awesome user experiences for web and mobile.